### ISSUE TITLE
incorrectly formatted line in index file (line 1)

### ISSUE THREAD

**Issue by companje** [Doodle3D/doodle3d-client#263]
this wifibox has the newest firmware but shows this error in the console:
```UpdatePanel:checkStatus response:  Object {data: Object, msg: "incorrectly formatted line in index file (line 1)", status: "fail"} doodle3d-client.min.js:1
UpdatePanel:setState:  undefined  >  1 (  ) (in Access Point Mode:  undefined ) (newestVersion:  undefined ) (refresh:  false ) doodle3d-client.min.js:1
Printer:preheat: failed doodle3d-client.min.js:1```

**Comment by peteruithoven** [comment]
Looks like it requests the images index file, but it receives our redirect / 404 page. (Which includes the "success" text we need to prevent captive portal popups on iOS devices)
This only happens when the WiFi-Box is in access point mode.
 
We should add a check and return a more appropriate error. 
Maybe this check can be added to d3d-updater's downloadFile function.

**Comment by peteruithoven** [comment]
Moved: https://github.com/Doodle3D/doodle3d-firmware/issues/48
